# Auto-generated by EnergyDSLCompiler

from pulp import LpMinimize, LpProblem

from app.infra.relation import Relation
from app.model.generator.generator import Generator
from app.model.model import Model
from app.model.grid_component.bus import Bus, BusType
from app.model.grid_component.line import Line
from app.model.generator.pv import PV
from app.model.generator.wind_turbine import Wind
from app.model.storage.battery import Battery
from app.model.load.load import Load
from app.model.slack import Slack
from app.model.storage.hot_water_storage import HotWaterStorage
from app.model.transducer.transducer import Transducer

Bus.default_nominal_voltage = 400
bus_MV = Bus(
    id="bus_MV",
    phase="3",
    type="SLACK",
    nominal_voltage=10000,
)
bus_LV1 = Bus(
    id="bus_LV1",
)
bus_LV2 = Bus(
    id="bus_LV2",
    phase="C",
)
bus_LV3 = Bus(
    id="bus_LV3",
    phase="3",
)

Line.default_line_length = 0.1
Line.default_resistance = 0.05
Line.default_reactance = 0.1
line1 = Line(
    id="line1",
    from_bus="bus_MV",
    to_bus="bus_LV1",
)
line2 = Line(
    id="line2",
    from_bus="bus_LV1",
    to_bus="bus_LV2",
)
line3 = Line(
    id="line3",
    from_bus="bus_LV1",
    to_bus="bus_LV3",
)


Generator.default_efficiency = 0.9

pv1 = PV(
    id="pv1",
    on="bus_LV1",
    peak_power=4,
    power={"input_path": "data/input.csv"},
)
pv2 = PV(
    id="pv2",
    on="bus_LV2",
    peak_power=3,
    power={"input_path": "input/pv2.csv"},
)

wind1 = Wind(
    id="wind1",
    on="bus_LV3",
    peak_power=5,
    efficiency=0.95,
    power={"input_path": "data/input.csv", "col": "wind"},
)


battery1 = Battery(
    id="battery1",
    on="bus_LV3",
    capacity=5,
    max_charge_rate=2,
    max_discharge_rate=2,
    charge_efficiency=0.95,
    discharge_efficiency=0.95,
    storage_efficiency=0.995,
)

hot_water1 = HotWaterStorage(
    id="hot_water1",
    on="bus_LV1",
    volume=120,
    set_temperature=60,
    heat={"input_path": "input/input.csv"},
)
hot_water2 = HotWaterStorage(
    id="hot_water2",
    on="bus_LV2",
    volume=200,
    max_charge_rate=2,
    max_discharge_rate=2,
    set_temperature=55,
    heat={"input_path": "input/hot_water2.csv"},
)

load1 = Load(
    id="load1",
    on="bus_LV1",
    power={"input_path": "input/load1.csv"},
)
load2 = Load(
    id="load2",
    on="bus_LV2",
    p_cons={"input_path": "input/load2.csv"},
)

heater1 = Transducer(
    id="heater1",
    on="bus_LV1",
    charges="hot_water1",
)
heater2 = Transducer(
    id="heater2",
    on="bus_LV2",
    charges="hot_water2",
)

slack = Slack(
    id="slack",
    on="bus_MV",
)


model = Model(
    id="Energy_Community",
    start="2025-01-01 00:00",
    end="2025-01-02 00:00",
    resolution="1h",
    entities=[
        bus_MV,
        bus_LV1,
        bus_LV2,
        bus_LV3,
        line1,
        line2,
        line3,
        pv1,
        pv2,
        wind1,
        battery1,
        hot_water1,
        hot_water2,
        load1,
        load2,
        heater1,
        heater2,
        slack,
    ],
)
